###Задание 1.

###A) Попробуйте различные варианты генерации кандидатов. Какие из них дают наибольший recall@k ?
- Пока пробуем отобрать 50 кандидатов (k=50)
- Качество измеряем на data_val_matcher: следующие 6 недель после трейна

###Дают ли own recommendtions + top-popular лучший recall?

###B)* Как зависит recall@k от k? Постройте для одной схемы генерации кандидатов эту зависимость для k = {20, 50, 100, 200, 500}

###C)* Исходя из прошлого вопроса, как вы думаете, какое значение k является наиболее разумным?

In [1]:
!pip install implicit

Requirement already satisfied: implicit in /usr/local/lib/python3.10/dist-packages (0.7.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from implicit) (1.22.4)
Requirement already satisfied: scipy>=0.16 in /usr/local/lib/python3.10/dist-packages (from implicit) (1.10.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from implicit) (4.65.0)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import OneHotEncoder

# Для работы с матрицами
from scipy.sparse import csr_matrix, coo_matrix
import implicit

# Матричная факторизация
from implicit import als

# Модель второго уровня
from lightgbm import LGBMClassifier

import os, sys
module_path = os.path.abspath(os.path.join(os.pardir))
if module_path not in sys.path:
    sys.path.append(module_path)

# Написанные нами функции
from src.metrics import precision_at_k, recall_at_k
from src.utils import prefilter_items
from src.recommenders import MainRecommender

/usr/local/lib/python3.10/dist-packages/implicit/gpu/__init__.py:13: UserWarning: CUDA extension is built, but disabling GPU support because of 'Cuda Error: CUDA driver version is insufficient for CUDA runtime version (/project/./implicit/gpu/utils.h:71)'
  warnings.warn(

In [3]:
data = pd.read_csv('retail_train.csv')
item_features = pd.read_csv('product.csv')
user_features = pd.read_csv('hh_demographic.csv')

# column processing
item_features.columns = [col.lower() for col in item_features.columns]
user_features.columns = [col.lower() for col in user_features.columns]

item_features.rename(columns={'product_id': 'item_id'}, inplace=True)
user_features.rename(columns={'household_key': 'user_id'}, inplace=True)


# Важна схема обучения и валидации!
# -- давние покупки -- | -- 6 недель -- | -- 3 недель --
# подобрать размер 2-ого датасета (6 недель) --> learning curve (зависимость метрики recall@k от размера датасета)
val_lvl_1_size_weeks = 6
val_lvl_2_size_weeks = 3

data_train_lvl_1 = data[data['week_no'] < data['week_no'].max() - (val_lvl_1_size_weeks + val_lvl_2_size_weeks)]
data_val_lvl_1 = data[(data['week_no'] >= data['week_no'].max() - (val_lvl_1_size_weeks + val_lvl_2_size_weeks)) &
                      (data['week_no'] < data['week_no'].max() - (val_lvl_2_size_weeks))]

data_train_lvl_2 = data_val_lvl_1.copy()  # Для наглядности. Далее мы добавим изменения, и они будут отличаться
data_val_lvl_2 = data[data['week_no'] >= data['week_no'].max() - val_lvl_2_size_weeks]

data_train_lvl_1.head(2)

,user_id,basket_id,day,item_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc
0,2375,26984851472,1,1004906,1,1.39,364,-0.6,1631,1,0.0,0.0
1,2375,26984851472,1,1033142,1,0.82,364,0.0,1631,1,0.0,0.0

In [4]:
def get_result_table(data: pd.DataFrame):
    result = data.groupby('user_id')['item_id'].unique().reset_index()
    result.columns = ['user_id', 'actual']
    return result

result_lvl_1 = get_result_table(data_val_lvl_1)
result_lvl_2 = get_result_table(data_val_lvl_2)
display(result_lvl_1.head(2), result_lvl_2.head(2))

   user_id                                             actual
0        1  [853529, 865456, 867607, 872137, 874905, 87524...
1        2  [15830248, 838136, 839656, 861272, 866211, 870...

   user_id                                             actual
0        1  [821867, 834484, 856942, 865456, 889248, 90795...
1        3  [835476, 851057, 872021, 878302, 879948, 90963...

In [5]:
n_items_before = data_train_lvl_1['item_id'].nunique()

data_train_lvl_1, top_n_popular = prefilter_items(data_train_lvl_1, item_features=item_features, take_n_popular=5000)

n_items_after = data_train_lvl_1['item_id'].nunique()
print('Decreased # items from {} to {}'.format(n_items_before, n_items_after))

Decreased # items from 83685 to 10086

In [6]:
common_users = data_train_lvl_1.user_id.values

data_val_lvl_1 = data_val_lvl_1[data_val_lvl_1.user_id.isin(common_users)]
data_train_lvl_2 = data_train_lvl_2[data_train_lvl_2.user_id.isin(common_users)]
data_val_lvl_2 = data_val_lvl_2[data_val_lvl_2.user_id.isin(common_users)]

In [7]:
recommender = MainRecommender(data_train_lvl_1, top_n_popular)

  0%|          | 0/15 [00:00<?, ?it/s]

  0%|          | 0/5001 [00:00<?, ?it/s]

In [8]:
model_recs = recommender.get_model_recommendation()

In [9]:
similar_items_recs = recommender.get_similar_items_recommendation()

In [10]:
recall_at_k_dict = {}

k_list = [20, 50, 100, 200, 500]

for k in k_list:
    comp_name = 'model_rec_' + str(k)

    model_recs = \
        recommender.get_model_recommendation(N=k)

    result_lvl_1 = result_lvl_1.merge(model_recs,
                                      on='user_id',
                                      how='inner').rename(columns={'model_rec': comp_name})

    recall_at_k_dict[comp_name] = \
        result_lvl_1.apply(lambda row: recall_at_k(row[comp_name],
                                                   row['actual'], k=k), axis=1).mean()

In [11]:
recall_at_k_dict

{'model_rec_20': 0.034544240565789225,
 'model_rec_50': 0.06491867659665028,
 'model_rec_100': 0.10009991957556608,
 'model_rec_200': 0.1456396739752215,
 'model_rec_500': 0.22993867251783626}

In [12]:
for k in k_list:
    comp_name = 'similar_recommendation_' + str(k)

    similar_items_recs = \
        recommender.get_similar_items_recommendation(N=k)

    result_lvl_1 = result_lvl_1.merge(similar_items_recs,
                                      on='user_id',
                                      how='inner').rename(columns={'similar_recommendation': comp_name})

    recall_at_k_dict[comp_name] = \
        result_lvl_1.apply(lambda row: recall_at_k(row[comp_name],
                                                   row['actual'], k=k), axis=1).mean()

In [13]:
recall_at_k_dict

{'model_rec_20': 0.034544240565789225,
 'model_rec_50': 0.06491867659665028,
 'model_rec_100': 0.10009991957556608,
 'model_rec_200': 0.1456396739752215,
 'model_rec_500': 0.22993867251783626,
 'similar_recommendation_20': 0.02588991519376351,
 'similar_recommendation_50': 0.049275628510994096,
 'similar_recommendation_100': 0.08204219383676527,
 'similar_recommendation_200': 0.13257666518009345,
 'similar_recommendation_500': 0.21672874335172748}

###На первом уровне лучший результат показала модель ALS при к = 500  с параметрами n_factors=20, regularization=0.001, iterations=15, num_threads=4

##Задание 2.

###Обучите модель 2-ого уровня, при этом:

###Добавьте минимум по 2 фичи для юзера, товара и пары юзер-товар

###Измерьте отдельно precision@5 модели 1-ого уровня и двухуровневой модели на data_val_ranker

###Вырос ли precision@5 при использовании двухуровневой модели?

In [14]:
#формируем датафрэйм для 2-ого уровня
users_lvl_2 = pd.DataFrame(data_train_lvl_2['user_id'].unique())
users_lvl_2.columns = ['user_id']

# Пока только warm start
train_users = data_train_lvl_1['user_id'].unique()
users_lvl_2 = users_lvl_2[users_lvl_2['user_id'].isin(train_users)]

In [15]:
users_lvl_2 = users_lvl_2.merge(recommender.get_model_recommendation(N=500),
                                on='user_id',
                                how='inner')

users_lvl_2.columns = ['user_id', 'candidates']
users_lvl_2.head(2)

   user_id                                         candidates
0     2070  [1107553, 1085604, 908531, 883404, 879755, 923...
1     2021  [871756, 896938, 951590, 981521, 1037863, 9985...

In [16]:
#Разворачиваем кандидатов, чтобы в каждой строке был только один:
s = users_lvl_2.apply(lambda x: pd.Series(x['candidates']), axis=1).stack().reset_index(level=1, drop=True)
s.name = 'item_id'

users_lvl_2 = users_lvl_2.drop('candidates', axis=1).join(s)
users_lvl_2['flag'] = 1

users_lvl_2.head(4)

   user_id  item_id  flag
0     2070  1107553     1
0     2070  1085604     1
0     2070   908531     1
0     2070   883404     1

In [17]:
data_train_lvl_2.head(2)

,user_id,basket_id,day,item_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc
2104867,2070,40618492260,594,1019940,1,1.00,311,-0.29,40,86,0.0,0.0
2107468,2021,40618753059,594,840361,1,0.99,443,0.00,101,86,0.0,0.0

In [18]:
targets_lvl_2 = data_train_lvl_2[['user_id', 'item_id', 'quantity', 'sales_value']].copy()
targets_lvl_2['target'] = 1  # тут только покупки

targets_lvl_2 = users_lvl_2.merge(targets_lvl_2, on=['user_id', 'item_id'], how='left')

targets_lvl_2['target'].fillna(0, inplace= True)
targets_lvl_2.drop('flag', axis=1, inplace=True)

targets_lvl_2.head(2)

   user_id  item_id  quantity  sales_value  target
0     2070  1107553       NaN          NaN     0.0
1     2070  1085604       1.0         1.11     1.0

In [19]:
item_features.info(), user_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92353 entries, 0 to 92352
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   item_id               92353 non-null  int64
 1   manufacturer          92353 non-null  int64
 2   department            92353 non-null  object
 3   brand                 92353 non-null  object
 4   commodity_desc        92353 non-null  object
 5   sub_commodity_desc    92353 non-null  object
 6   curr_size_of_product  92353 non-null  object
dtypes: int64(2), object(5)
memory usage: 4.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age_desc             801 non-null    object
 1   marital_status_code  801 non-null    object
 2   income_desc          801 non-null    object
 3   homeowner_desc       801 non-null    object
 4   hh_comp_desc         801 non-null    object
 5   household_size_desc  801 non-null    object
 6   kid_category_desc    801 non-null    object
 7   user_id              801 non-null    int64
dtypes: int64(1), object(7)
memory usage: 50.2+ KB

(None, None)

In [20]:
targets_lvl_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1080484 entries, 0 to 1080483
Data columns (total 5 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   user_id      1080484 non-null  int64
 1   item_id      1080484 non-null  int64
 2   quantity     42676 non-null    float64
 3   sales_value  42676 non-null    float64
 4   target       1080484 non-null  float64
dtypes: float64(3), int64(2)
memory usage: 49.5 MB

In [21]:
## Подготавливаем фичи для обучения модели
targets_lvl_2 = targets_lvl_2.merge(item_features, on='item_id', how='left')
targets_lvl_2 = targets_lvl_2.merge(user_features, on='user_id', how='left')

targets_lvl_2.head(2)

,user_id,item_id,quantity,sales_value,target,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,age_desc,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc
0,2070,1107553,NaN,NaN,0.0,103,GROCERY,National,SOFT DRINKS,SFT DRNK SNGL SRV BTL CARB (EX,20 OZ,45-54,U,50-74K,Unknown,Unknown,1,None/Unknown
1,2070,1085604,1.0,1.11,1.0,103,GROCERY,National,SOFT DRINKS,SFT DRNK SNGL SRV BTL CARB (EX,20 OZ,45-54,U,50-74K,Unknown,Unknown,1,None/Unknown

In [22]:
targets_lvl_2['quantity'].fillna(targets_lvl_2['quantity'].median(),
                                 inplace=True)
targets_lvl_2['sales_value'].fillna(targets_lvl_2['sales_value'].mean(),
                                    inplace=True)

targets_lvl_2.info(2)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1080484 entries, 0 to 1080483
Data columns (total 18 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   user_id               1080484 non-null  int64
 1   item_id               1080484 non-null  int64
 2   quantity              1080484 non-null  float64
 3   sales_value           1080484 non-null  float64
 4   target                1080484 non-null  float64
 5   manufacturer          1080484 non-null  int64
 6   department            1080484 non-null  object
 7   brand                 1080484 non-null  object
 8   commodity_desc        1080484 non-null  object
 9   sub_commodity_desc    1080484 non-null  object
 10  curr_size_of_product  1080484 non-null  object
 11  age_desc              401666 non-null   object
 12  marital_status_code   401666 non-null   object
 13  income_desc           401666 non-null   object
 14  homeowner_desc        401666 non-null   object
 15  hh_comp_desc          401666 non-null   object
 16  household_size_desc   401666 non-null   object
 17  kid_category_desc     401666 non-null   object
dtypes: float64(3), int64(3), object(12)
memory usage: 156.6+ MB

In [23]:
#Топ категорий товаров, которые купил пользователь.
df = pd.pivot_table(targets_lvl_2,
                    index='user_id', columns='department',
                    values='quantity',
                    aggfunc='count',
                    fill_value=0)

df = df.idxmax(axis=1).reset_index()
df.columns = ['user_id', 'top_department']

targets_lvl_2 = targets_lvl_2.merge(df,
                                    on='user_id',
                                    how='inner')

In [24]:
#Топ брендов, которые купил пользователь.
df = pd.pivot_table(targets_lvl_2,
                    index='user_id', columns='brand',
                    values='quantity',
                    aggfunc='count',
                    fill_value=0)

df = df.idxmax(axis=1).reset_index()
df.columns = ['user_id', 'top_brand']

targets_lvl_2 = targets_lvl_2.merge(df,
                                    on='user_id',
                                    how='inner')

In [25]:
# # Средняя сумма чека пользователя в каждой категории товаров (department)
df = pd.pivot_table(targets_lvl_2,
                    index='user_id', columns='department',
                    values='sales_value',
                    aggfunc='mean',
                    fill_value=0
                    )

df = df.stack().reset_index()
df.columns = ['user_id', 'department', 'mean_sales_value_of_user_in_department']

targets_lvl_2 = targets_lvl_2.merge(df,
                                    on=['user_id', 'department'],
                                    how='inner')

In [26]:
targets_lvl_2['age_desc'].unique()

array(['45-54', nan, '35-44', '55-64', '25-34', '65+', '19-24'],
      dtype=object)

In [27]:
df = \
    targets_lvl_2.groupby(by=['user_id'])['age_desc']\
    .apply(lambda x: pd.Series.mode(x))
df = df.reset_index()
df.drop(columns='level_1',
        inplace=True)

df.columns=['user_id', 'age_desc_corrected']

targets_lvl_2 = targets_lvl_2.merge(df,
                                    on='user_id',
                                    how='inner')

In [28]:
targets_lvl_2.head(2)

,user_id,item_id,quantity,sales_value,target,manufacturer,department,brand,commodity_desc,sub_commodity_desc,...,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,top_department,top_brand,mean_sales_value_of_user_in_department,age_desc_corrected
0,2070,1107553,1.0,2.432181,0.0,103,GROCERY,National,SOFT DRINKS,SFT DRNK SNGL SRV BTL CARB (EX,...,U,50-74K,Unknown,Unknown,1,None/Unknown,GROCERY,National,2.365212,45-54
1,2070,1085604,1.0,1.110000,1.0,103,GROCERY,National,SOFT DRINKS,SFT DRNK SNGL SRV BTL CARB (EX,...,U,50-74K,Unknown,Unknown,1,None/Unknown,GROCERY,National,2.365212,45-54

In [29]:
targets_lvl_2.columns

Index(['user_id', 'item_id', 'quantity', 'sales_value', 'target',
       'manufacturer', 'department', 'brand', 'commodity_desc',
       'sub_commodity_desc', 'curr_size_of_product', 'age_desc',
       'marital_status_code', 'income_desc', 'homeowner_desc', 'hh_comp_desc',
       'household_size_desc', 'kid_category_desc', 'top_department',
       'top_brand', 'mean_sales_value_of_user_in_department',
       'age_desc_corrected'],
      dtype='object')

In [30]:
feature_columns = \
    ['user_id',
     'item_id',
     'quantity',
     'sales_value',
     'department',
     'manufacturer',
     'age_desc_corrected',
     'brand',
     'top_department',
     'top_brand',
     'mean_sales_value_of_user_in_department'
    ]

In [31]:
targets_lvl_2[feature_columns].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 401666 entries, 0 to 401665
Data columns (total 11 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   user_id                                 401666 non-null  int64
 1   item_id                                 401666 non-null  int64
 2   quantity                                401666 non-null  float64
 3   sales_value                             401666 non-null  float64
 4   department                              401666 non-null  object
 5   manufacturer                            401666 non-null  int64
 6   age_desc_corrected                      401666 non-null  object
 7   brand                                   401666 non-null  object
 8   top_department                          401666 non-null  object
 9   top_brand                               401666 non-null  object
 10  mean_sales_value_of_user_in_department  401666 non-null  float64
dtypes: float64(3), int64(3), object(5)
memory usage: 36.8+ MB

In [32]:
X_train = targets_lvl_2[feature_columns]
y_train = targets_lvl_2['target']

X_train.head(2)

,user_id,item_id,quantity,sales_value,department,manufacturer,age_desc_corrected,brand,top_department,top_brand,mean_sales_value_of_user_in_department
0,2070,1107553,1.0,2.432181,GROCERY,103,45-54,National,GROCERY,National,2.365212
1,2070,1085604,1.0,1.110000,GROCERY,103,45-54,National,GROCERY,National,2.365212

In [33]:
cat_feats = ['user_id', 'item_id', 'manufacturer',
              'age_desc_corrected', 'department',
             'brand', 'top_department','top_brand']

X_train[cat_feats] = X_train[cat_feats].astype('category')

<ipython-input-33-3737d75b8fd4>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[cat_feats] = X_train[cat_feats].astype('category')

In [34]:
X_train.isna().sum()

user_id                                   0
item_id                                   0
quantity                                  0
sales_value                               0
department                                0
manufacturer                              0
age_desc_corrected                        0
brand                                     0
top_department                            0
top_brand                                 0
mean_sales_value_of_user_in_department    0
dtype: int64

In [35]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.10/dist-packages (1.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.22.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.10.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.13.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2022.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.40.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (8.2.2)

In [36]:
from catboost import CatBoostClassifier

In [37]:
result_lvl_2 = data_val_lvl_2.groupby('user_id')['item_id'].unique().reset_index()
result_lvl_2.columns = ['user_id', 'actual']
result_lvl_2.head(5)

   user_id                                             actual
0        1  [821867, 834484, 856942, 865456, 889248, 90795...
1        3  [835476, 851057, 872021, 878302, 879948, 90963...
2        6  [920308, 926804, 946489, 1006718, 1017061, 107...
3        7  [840386, 889774, 898068, 909714, 929067, 95347...
4        8  [835098, 872137, 910439, 924610, 992977, 10412...

In [38]:
def map_at_k(recommended_list, bought_list, k=5):
    flags = np.isin(np.array(recommended_list), np.array(bought_list))
    if sum(flags) == 0:
        return 0
    sum_ = 0
    for i in range(min(k, len(flags))):
        if flags[i]:
            p_k = precision_at_k(recommended_list, bought_list, k=i+1)
            sum_ += p_k
    return sum_ / k

In [39]:
table_metric = {'iterations':[], 'learning_rate':[], 'depth':[],'Precision@5':[], 'MAP@5':[]}

for iterations_ in [50, 150, 300]:
  for learning_rate_ in [0.001, 0.015, 0.05]:
    for depth_ in [5, 10, 15]:
      model_ = CatBoostClassifier(
        random_seed=55,
        iterations=iterations_,
        learning_rate=learning_rate_,
        depth=depth_)

      model_.fit(X_train, y_train,
              cat_features=cat_feats,
              verbose=50)
      train_preds_ = model_.predict(X_train)
      train_preds_ = train_preds_.astype(bool)

      rec_items_ = X_train[train_preds_].groupby(by=['user_id'])['item_id'].unique().reset_index()
      rec_items_.columns = ['user_id', f'model_preds_iter_{iterations_}_rate{learning_rate_}_depth{depth_}']

      rec_items_[f'model_preds_iter_{iterations_}_rate{learning_rate_}_depth{depth_}'] = \
      rec_items_[f'model_preds_iter_{iterations_}_rate{learning_rate_}_depth{depth_}'].apply(lambda x: x[:5] if len(x) >= 5 else x)

      result_lvl_2 = result_lvl_2.merge(rec_items_,
                                   on='user_id',
                                   how='inner')

      test_presicion_ = result_lvl_2.apply(lambda row: precision_at_k(row[f'model_preds_iter_{iterations_}_rate{learning_rate_}_depth{depth_}'], row['actual']), axis=1).mean()
      test_map = result_lvl_2.apply(lambda row:  map_at_k(row[f'model_preds_iter_{iterations_}_rate{learning_rate_}_depth{depth_}'], row['actual']), axis=1).mean()

      table_metric['iterations'].append(iterations_)
      table_metric['learning_rate'].append(learning_rate_)
      table_metric['depth'].append(depth_)
      table_metric['Precision@5'].append(test_presicion_)
      table_metric['MAP@5'].append(test_map)

0:	learn: 0.6921508	total: 258ms	remaining: 12.7s
49:	learn: 0.6455842	total: 7.03s	remaining: 0us
0:	learn: 0.6921508	total: 295ms	remaining: 14.5s
49:	learn: 0.6455989	total: 9.74s	remaining: 0us
0:	learn: 0.6921508	total: 120ms	remaining: 5.89s
49:	learn: 0.6456107	total: 6.09s	remaining: 0us
0:	learn: 0.6783055	total: 121ms	remaining: 5.92s
49:	learn: 0.2689866	total: 5.03s	remaining: 0us
0:	learn: 0.6783055	total: 121ms	remaining: 5.91s
49:	learn: 0.2689916	total: 5.2s	remaining: 0us
0:	learn: 0.6783055	total: 117ms	remaining: 5.74s
49:	learn: 0.2690230	total: 7.36s	remaining: 0us
0:	learn: 0.6445466	total: 111ms	remaining: 5.42s
49:	learn: 0.0414402	total: 4.3s	remaining: 0us
0:	learn: 0.6445466	total: 223ms	remaining: 10.9s
49:	learn: 0.0414844	total: 5.49s	remaining: 0us
0:	learn: 0.6445466	total: 113ms	remaining: 5.54s
49:	learn: 0.0414476	total: 6.58s	remaining: 0us
0:	learn: 0.6921508	total: 125ms	remaining: 18.6s
50:	learn: 0.6446783	total: 4.22s	remaining: 8.19s
100:	learn: 0.6015227	total: 8.36s	remaining: 4.06s
149:	learn: 0.5628902	total: 13.1s	remaining: 0us
0:	learn: 0.6921508	total: 115ms	remaining: 17.2s
50:	learn: 0.6446947	total: 5.09s	remaining: 9.88s
100:	learn: 0.6015452	total: 10.7s	remaining: 5.21s
149:	learn: 0.5629164	total: 15.8s	remaining: 0us
0:	learn: 0.6921508	total: 119ms	remaining: 17.7s
50:	learn: 0.6447050	total: 7s	remaining: 13.6s
100:	learn: 0.6015634	total: 12s	remaining: 5.81s
149:	learn: 0.5629215	total: 18.1s	remaining: 0us
0:	learn: 0.6783055	total: 109ms	remaining: 16.3s
50:	learn: 0.2643959	total: 4.29s	remaining: 8.32s
100:	learn: 0.1163302	total: 9.24s	remaining: 4.49s
149:	learn: 0.0541541	total: 13.3s	remaining: 0us
0:	learn: 0.6783055	total: 116ms	remaining: 17.2s
50:	learn: 0.2644014	total: 5.76s	remaining: 11.2s
100:	learn: 0.1163580	total: 10.7s	remaining: 5.18s
149:	learn: 0.0541787	total: 16.5s	remaining: 0us
0:	learn: 0.6783055	total: 116ms	remaining: 17.2s
50:	learn: 0.2644359	total: 7.24s	remaining: 14s
100:	learn: 0.1163660	total: 12.9s	remaining: 6.25s
149:	learn: 0.0541957	total: 18.9s	remaining: 0us
0:	learn: 0.6445466	total: 116ms	remaining: 17.2s
50:	learn: 0.0393842	total: 5.2s	remaining: 10.1s
100:	learn: 0.0032093	total: 9.76s	remaining: 4.73s
149:	learn: 0.0002993	total: 15.1s	remaining: 0us
0:	learn: 0.6445466	total: 115ms	remaining: 17.1s
50:	learn: 0.0394227	total: 5.21s	remaining: 10.1s
100:	learn: 0.0032145	total: 11.6s	remaining: 5.62s
149:	learn: 0.0003028	total: 17.5s	remaining: 0us
0:	learn: 0.6445466	total: 120ms	remaining: 18s
50:	learn: 0.0393866	total: 6.66s	remaining: 12.9s
100:	learn: 0.0032239	total: 14.4s	remaining: 7s
149:	learn: 0.0003030	total: 20.5s	remaining: 0us
0:	learn: 0.6895136	total: 269ms	remaining: 1m 20s
50:	learn: 0.5055109	total: 14.6s	remaining: 1m 11s
100:	learn: 0.3691222	total: 29.9s	remaining: 58.9s
150:	learn: 0.2653817	total: 43.8s	remaining: 43.2s
200:	learn: 0.1915594	total: 57.6s	remaining: 28.4s
250:	learn: 0.1360809	total: 1m 12s	remaining: 14.1s
299:	learn: 0.0955793	total: 1m 27s	remaining: 0us
0:	learn: 0.6895136	total: 265ms	remaining: 1m 19s
50:	learn: 0.5062871	total: 18.1s	remaining: 1m 28s
100:	learn: 0.3630070	total: 38.6s	remaining: 1m 16s
150:	learn: 0.2594154	total: 59.7s	remaining: 58.9s
200:	learn: 0.1843622	total: 1m 19s	remaining: 39.1s
250:	learn: 0.1303865	total: 1m 39s	remaining: 19.4s
299:	learn: 0.0931324	total: 2m	remaining: 0us
0:	learn: 0.6895136	total: 278ms	remaining: 1m 23s
50:	learn: 0.5101694	total: 20.1s	remaining: 1m 38s
100:	learn: 0.3678978	total: 38.4s	remaining: 1m 15s
150:	learn: 0.2637597	total: 1m	remaining: 59.3s
200:	learn: 0.1856733	total: 1m 22s	remaining: 40.5s
250:	learn: 0.1308816	total: 1m 45s	remaining: 20.6s
299:	learn: 0.0918951	total: 2m 2s	remaining: 0us
0:	learn: 0.6400449	total: 358ms	remaining: 1m 47s
50:	learn: 0.0032199	total: 14.7s	remaining: 1m 11s
100:	learn: 0.0001068	total: 27s	remaining: 53.2s
150:	learn: 0.0000260	total: 38.8s	remaining: 38.3s
200:	learn: 0.0000150	total: 50.2s	remaining: 24.7s
250:	learn: 0.0000114	total: 1m 2s	remaining: 12.2s
299:	learn: 0.0000110	total: 1m 15s	remaining: 0us
0:	learn: 0.6400449	total: 269ms	remaining: 1m 20s
50:	learn: 0.0032068	total: 20.9s	remaining: 1m 42s
100:	learn: 0.0001380	total: 43s	remaining: 1m 24s
150:	learn: 0.0000375	total: 1m 7s	remaining: 1m 6s
200:	learn: 0.0000216	total: 1m 30s	remaining: 44.6s
250:	learn: 0.0000166	total: 1m 52s	remaining: 22s
299:	learn: 0.0000157	total: 2m 14s	remaining: 0us
0:	learn: 0.6400449	total: 277ms	remaining: 1m 22s
50:	learn: 0.0032537	total: 20.2s	remaining: 1m 38s
100:	learn: 0.0001506	total: 40.7s	remaining: 1m 20s
150:	learn: 0.0000393	total: 1m 5s	remaining: 1m 5s
200:	learn: 0.0000216	total: 1m 29s	remaining: 44s
250:	learn: 0.0000157	total: 1m 52s	remaining: 21.9s
299:	learn: 0.0000155	total: 2m 15s	remaining: 0us
0:	learn: 0.5277296	total: 270ms	remaining: 1m 20s
50:	learn: 0.0000223	total: 13.4s	remaining: 1m 5s
100:	learn: 0.0000106	total: 24.6s	remaining: 48.5s
150:	learn: 0.0000103	total: 34.9s	remaining: 34.5s
200:	learn: 0.0000103	total: 45.5s	remaining: 22.4s
250:	learn: 0.0000103	total: 55.9s	remaining: 10.9s
299:	learn: 0.0000103	total: 1m 5s	remaining: 0us
0:	learn: 0.5277296	total: 272ms	remaining: 1m 21s
50:	learn: 0.0000292	total: 22.2s	remaining: 1m 48s
100:	learn: 0.0000173	total: 42.1s	remaining: 1m 22s
150:	learn: 0.0000173	total: 1m 4s	remaining: 1m 3s
200:	learn: 0.0000173	total: 1m 24s	remaining: 41.6s
250:	learn: 0.0000173	total: 1m 43s	remaining: 20.2s
299:	learn: 0.0000172	total: 2m 2s	remaining: 0us
0:	learn: 0.5277296	total: 278ms	remaining: 1m 23s
50:	learn: 0.0000292	total: 31.5s	remaining: 2m 33s
100:	learn: 0.0000198	total: 1m 5s	remaining: 2m 8s
150:	learn: 0.0000198	total: 1m 37s	remaining: 1m 36s
200:	learn: 0.0000198	total: 2m 9s	remaining: 1m 3s
250:	learn: 0.0000198	total: 2m 45s	remaining: 32.2s
299:	learn: 0.0000198	total: 3m 18s	remaining: 0us

In [40]:
table_metric = pd.DataFrame(table_metric)
table_metric.sort_values(by=['Precision@5'], ascending=False)

    iterations  learning_rate  depth  Precision@5     MAP@5
13         150          0.015     10     0.320504  0.228491
12         150          0.015      5     0.320504  0.228491
20         300          0.001     15     0.320504  0.228491
19         300          0.001     10     0.320504  0.228491
4           50          0.015     10     0.320504  0.228491
5           50          0.015     15     0.320504  0.228491
18         300          0.001      5     0.320504  0.228491
7           50          0.050     10     0.320504  0.228491
14         150          0.015     15     0.320504  0.228491
9          150          0.001      5     0.320504  0.228491
1           50          0.001     10     0.320504  0.228825
0           50          0.001      5     0.320241  0.228548
11         150          0.001     15     0.320241  0.228548
10         150          0.001     10     0.320241  0.228548
2           50          0.001     15     0.320241  0.228548
3           50          0.015      5     0.320241  0.228561
8           50          0.050     15     0.319978  0.228320
15         150          0.050      5     0.319978  0.228307
16         150          0.050     10     0.319978  0.228307
17         150          0.050     15     0.319978  0.228307
6           50          0.050      5     0.319978  0.228307
21         300          0.015      5     0.319978  0.228307
22         300          0.015     10     0.319978  0.228307
23         300          0.015     15     0.319978  0.228307
24         300          0.050      5     0.319978  0.228307
25         300          0.050     10     0.319978  0.228307
26         300          0.050     15     0.319978  0.228307

###На втором уровне наиболее оптимальными параметрами модели CatBoostClassifier являются: iterations = 50, learning_rate = 0,05 и depth = 10